#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChipFox.Resource", IsApplication=true)]

namespace ChipFox
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int button1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int button2 = 2130837505;
			
			// aapt resource value: 0x7F02000D
			public const int editText14 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int editText7 = 2130837518;
			
			// aapt resource value: 0x7F020002
			public const int eT_cutDepth = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int eT_cutSpd = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int eT_cutWidth = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int eT_forcedVc = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int eT_maxChipThickness = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int eT_medChipThickness = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int eT_splSpd = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int eT_toolDm = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int eT_toothFeed = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int eT_toothNbr = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int eT_totalFeed = 2130837516;
			
			// aapt resource value: 0x7F02000F
			public const int linearLayout1 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int relativeLayout1 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int scrollView1 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int textView10 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int textView11 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int textView12 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int textView13 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int textView14 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int textView25 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int textView3 = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int textView4 = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int textView5 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int textView6 = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int textView7 = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int textView8 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int textView9 = 2130837534;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int CutDepth = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int CutSpd = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int CutWidth = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ForcedVc = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Hello = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int MaxChipThickness = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int Reset = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ToolDm = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ToothFeed = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ToothNbr = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int TotalFeed = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
